增加“送礼物”和“上舰”行为处理
eric2788/dd_vup_stats pull request #4
Opened 2022-05-04 16:02 UTC by superrabbit11223344

目前对“送礼物”的行为处理还不够完善，后续会针对礼物数量进行限制、添加排行榜等

2022-05-06 09:17 UTC, eric2788 requested changes
從數據庫提取數據排行之類的沒有搞？這樣只能記錄沒辦法顯示

2022-05-06 09:17 UTC, eric2788 commented on handlers/guard_buy.go
> +		logger.Warnf("記錄醒目留言行為到資料庫失敗: %v", result.Error)
訊息不應該為醒目留言

2022-05-06 09:17 UTC, eric2788 commented on handlers/guard_buy.go
> +		logger.Infof("記錄醒目留言行為到資料庫成功。(%v 筆資料)", result.RowsAffected)
訊息不應該為醒目留言

2022-05-06 09:17 UTC, eric2788 commented on handlers/send_gift.go
> +	display := fmt.Sprintf("在 %s 的直播间收到来自 %s 的 %s (%v元)", data.LiveInfo.Name, gift.Uname, giftName, price)
缺少禮物數量?

2022-05-06 09:17 UTC, eric2788 commented on handlers/send_gift.go
> +func giftMsg(data *blive.LiveData) error {
建議添加過濾 0 元的東西 (例如小心心，可能造成洗屏)

2022-05-06 09:18 UTC, eric2788 commented on handlers/send_gift.go
> +		logger.Warnf("記錄醒目留言行為到資料庫失敗: %v", result.Error)
訊息不應為醒目留言

2022-05-06 09:18 UTC, eric2788 commented on handlers/send_gift.go
> +		logger.Infof("記錄醒目留言行為到資料庫成功。(%v 筆資料)", result.RowsAffected)
訊息不應為醒目留言

2022-05-13 02:59 UTC, eric2788 requested changes

2022-05-13 02:59 UTC, eric2788 commented on handlers/send_gift.go
> +	filter_gift_list := []string{"小心心", "辣条", "小花花"}
改成price == 0 比較好？因為之後可能會出其他免費禮物到時候又要新增就麻煩了

2022-05-13 03:11 UTC, superrabbit11223344 commented on handlers/send_gift.go
> +	filter_gift_list := []string{"小心心", "辣条", "小花花"}
已修改，将筛选条件改成"giftPrice == 0"

2022-05-13 03:24 UTC, eric2788 approved these changes

2022-05-13 03:24 UTC, merged